config/routes.rb
MyNsci::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }  do
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :computers, except: [:show] do
    member do
      get :key
    end
    resources :visits, only: [:index, :update]
  end

  get '/check/:key' => 'computers#check', as: :check

  match '*path' => 'application#render_404', via: [:get, :post]
  root to: 'computers#index'
end

app/models/visit.rb
class Visit
  include Mongoid::Document
  include Mongoid::Timestamps

  field :ip, default: '0.0.0.0'
  field :comment, default: ''

  belongs_to :computer
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visit }
      else
        format.html { render action: 'new' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:index)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.haml
= form_for @visit do |f|
  - if @visit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@visit.errors.count, "error")} prohibited this visit from being saved:"
      %ul
        - @visit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :index
    = f.text_field :index
  .actions
    = f.submit 'Save'

app/views/visits/edit.html.haml
%h1 Editing visit

= render 'form'

= link_to 'Show', @visit
\|
= link_to 'Back', visits_path

app/views/visits/index.html.haml
%h1 Listing visits

%table
  %tr
    %th Index
    %th
    %th
    %th

  - @visits.each do |visit|
    %tr
      %td= visit.index
      %td= link_to 'Show', visit
      %td= link_to 'Edit', edit_visit_path(visit)
      %td= link_to 'Destroy', visit, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Visit', new_visit_path

app/views/visits/new.html.haml
%h1 New visit

= render 'form'

= link_to 'Back', visits_path

app/views/visits/show.html.haml
%p#notice= notice

%p
  %b Index:
  = @visit.index

= link_to 'Edit', edit_visit_path(@visit)
\|
= link_to 'Back', visits_path