config/routes.rb
MyNsci::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }  do
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :computers, except: [:show] do
    member do
      get :key
    end
    resources :visits, only: [:index, :update]
  end

  get '/check/:key' => 'computers#check', as: :check

  match '*path' => 'application#render_404', via: [:get, :post]
  root to: 'computers#index'
end

app/models/computer.rb
class Computer
  include Mongoid::Document
  include Mongoid::Versioning

  max_versions 5

  resourcify

  field :name, default: ''
  field :ip, default: '0.0.0.0'
  field :key
  field :visited_at, default: Time.now

  field :comment, default: ''

  belongs_to :user
  has_many :visits

  before_create :generate_key

  def track! ip
    if self.ip != ip
      self.visits.create ip: ip
      self.ip = ip
      self.visited_at = Time.now
      self.save
    else
      self.versionless do |doc|
        doc.visited_at = Time.now
        doc.save
      end
    end
  end

  def generate_key
    self.key = Digest::MD5.hexdigest(SecureRandom.hex + self.id)
  end
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :check]
  before_action :set_computer, only: [:show, :edit, :update, :destroy, :key]
  authorize_resource except: [:index, :check]

  # GET /computers
  # GET /computers.json
  def index
    if signed_in?
      @computers = current_user.computers.all.decorate
      @computer = current_user.computers.new
    end
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = current_user.computers.new
  end

  # GET /computers/1/edit
  def edit
  end

  def key
    send_data render_to_string, :disposition => 'attachment'
  end

  def check
    begin
      @computer = Computer.where(key: params[:key]).first
      if @computer
        @computer.track! request.env['HTTP_X_REAL_IP'] || request.remote_ip

        render text: @computer.user.key, content_type: "text/plain"
      else
        render text: '', status: 404
      end

    rescue Mongoid::Errors::DocumentNotFound
      render text: '', status: 404
    end
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = current_user.computers.new(computer_params)

    respond_to do |format|
      if @computer.save
        current_user.add_role :owner, @computer
        format.html { redirect_to computers_path, notice: t('computer.created') }
        format.json { render action: 'show', status: :created, location: @computer }
      else
        format.html { render action: 'new' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      @computer.versionless do |doc|
        if doc.update(computer_params)
          format.html { redirect_to computers_path, notice: t('computer.updated') }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @computer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:name)
    end
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_computer.html.haml
%tr
  %td= computer.name
  %td= computer.ip if can? :manage, computer
  %td= computer.visited_at if can? :manage, computer
  %td
    .btn-group
      - if can? :read, computer
        = link_to key_computer_path(computer, format: 'reg'), class: 'btn btn-primary' do
          %i.glyphicon.glyphicon-save
          = t 'computer.key_install'
      = edit_link_to edit_computer_path(computer), role: 'button' if can? :manage, computer
      = destroy_link_to computer, role: 'button' if can? :manage, computer

app/views/computers/_form.html.haml
= form_for @computer, :html => {:class => "form-horizontal", :role=>"form"} do |f|
  %fieldset
    .form-group
      %label.col-md-3.control-label= Computer.human_attribute_name :name
      .col-md-6= f.text_field :name, :class => 'form-control'
    .form-group
      .col-md-offset-3.col-md-6
        = f.submit value: t('common.update'), class: 'btn btn-default'

app/views/computers/_list.html.haml
%table.table
  %thead
    %tr
      %th{:width => '40%'}= Computer.human_attribute_name :name
      %th= Computer.human_attribute_name :ip
      %th= Computer.human_attribute_name :visited_at
      %th
  %tbody
    = render @computers

#addComputerForm.modal.fade{:tabindex=>"-1", :role=>"dialog", :aria => { :labelledby=>"myModalLabel", :hidden=>"true"} }
  .modal-dialog
    .modal-content
      = form_for @computer do |f|
        .modal-header
          %button.close{:type=>"button", :data => {:dismiss=>"modal"},  :aria => {:hidden=>"true"}} &times
          %h4.modal-title= t 'computer.new'
        .modal-body
          %fieldset
            .form-group
              %label.col-md-3.control-label= Computer.human_attribute_name :name
              .col-md-9= f.text_field :name, :class => 'form-control'

        .modal-footer
          %button.btn.btn-default{:type=>"button", :data => {:dismiss=>"modal" }}= t 'common.cancel'
          = f.submit value: t('common.save'), class: 'btn btn-primary'

app/views/computers/edit.html.haml
%h1= t 'computer.edit'
= render 'form'
= link_to t('common.back'), computers_path, class: 'btn btn-default'

app/views/computers/index.html.haml
- if signed_in?
  %h1= t 'computer.list'
  = render 'list'

  = new_link_to t('computer.new'), new_computer_path(anchor: "addComputerForm"), :data => { :toggle=>"modal"}
  = link_to '/default.reg', class: 'btn btn-default' do
    %i.glyphicon.glyphicon-save
    = t('computer.default')

app/views/computers/key.reg.erb
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet]
"ActiveWebProbePathV6"="check/<%= @computer.key %>"
"ActiveWebProbeContentV6"="<%= current_user.key %>"
"ActiveDnsProbeContentV6"="fd3e:4f5a:5b81::1"
"ActiveWebProbeHostV6"="<%= request.host %>"
"ActiveDnsProbeHostV6"="dns.msftncsi.com"
"ActiveWebProbePath"="check/<%= @computer.key %>"
"ActiveDnsProbeHost"="dns.msftncsi.com"
"ActiveWebProbeContent"="<%= current_user.key %>"
"ActiveDnsProbeContent"="131.107.255.255"
"ActiveWebProbeHost"="<%= request.host %>"
"StaleThreshold"=dword:0000001e
"WebTimeout"=dword:00000023

app/views/computers/new.html.haml
%h1 New computer
= render 'form'
= link_to 'Back', computers_path

app/views/computers/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_computer_path(@computer)
|
\#{link_to 'Back', computers_path}